export default function TermsOfServicePage() {
  return (
    <div style={{ maxWidth: 800, margin: "0 auto", padding: "40px 24px", fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif" }}>
      <h1 style={{ fontSize: 32, fontWeight: 700, marginBottom: 8 }}>Terms of Service</h1>
      <p style={{ fontSize: 13, color: "#64748b", marginBottom: 32 }}>Last updated: July 25, 2026</p>

      <div style={{ fontSize: 15, lineHeight: 1.8, color: "#1e293b" }}>
        <h2 style={{ fontSize: 20, fontWeight: 600, marginTop: 32, marginBottom: 12 }}>1. Acceptance of Terms</h2>
        <p style={{ marginBottom: 16 }}>
          By installing and using MTS AI Business Intelligence ("the app"), you agree to these Terms of Service.
          The app is developed by MageTechSol ("we", "our").
        </p>

        <h2 style={{ fontSize: 20, fontWeight: 600, marginTop: 32, marginBottom: 12 }}>2. Service Description</h2>
        <p style={{ marginBottom: 16 }}>
          MTS AI Business Intelligence provides analytics, business insights, and AI-powered recommendations
          for Shopify stores. The app syncs your store data (orders, products, customers) and generates
          dashboards, reports, and forecasts.
        </p>

        <h2 style={{ fontSize: 20, fontWeight: 600, marginTop: 32, marginBottom: 12 }}>3. Billing & Subscriptions</h2>
        <p style={{ marginBottom: 12 }}>The app offers two pricing tiers:</p>
        <ul style={{ marginBottom: 16, paddingLeft: 24 }}>
          <li style={{ marginBottom: 8 }}><strong>Free Plan:</strong> Includes dashboard overview, basic sales analytics, and settings access at no cost.</li>
          <li style={{ marginBottom: 8 }}><strong>Pro Plan ($29/month):</strong> Includes all features including advanced product analytics, customer segmentation, inventory monitoring, AI insights, and revenue forecasting.</li>
        </ul>
        <p style={{ marginBottom: 16 }}>
          All billing is handled through Shopify's billing system. Charges appear on your Shopify invoice.
          You may cancel your Pro subscription at any time from your Shopify admin. Cancellation takes effect
          at the end of the current billing cycle.
        </p>

        <h2 style={{ fontSize: 20, fontWeight: 600, marginTop: 32, marginBottom: 12 }}>4. Data Usage</h2>
        <p style={{ marginBottom: 16 }}>
          Your store data is used solely to provide the app's analytics and insight features. We do not sell
          or share your data with third parties. See our Privacy Policy for complete details.
        </p>

        <h2 style={{ fontSize: 20, fontWeight: 600, marginTop: 32, marginBottom: 12 }}>5. AI-Generated Content</h2>
        <p style={{ marginBottom: 16 }}>
          AI-powered insights are generated by artificial intelligence and may not always be accurate.
          These insights are provided for informational purposes only and should not be considered as
          professional business or financial advice. You are responsible for evaluating and acting on
          any insights provided by the app.
        </p>

        <h2 style={{ fontSize: 20, fontWeight: 600, marginTop: 32, marginBottom: 12 }}>6. Limitation of Liability</h2>
        <p style={{ marginBottom: 16 }}>
          To the maximum extent permitted by law, MageTechSol shall not be liable for any indirect, incidental,
          special, or consequential damages arising from your use of the app. Our total liability shall not exceed
          the amount you paid for the app in the 12 months preceding the claim.
        </p>

        <h2 style={{ fontSize: 20, fontWeight: 600, marginTop: 32, marginBottom: 12 }}>7. Termination</h2>
        <p style={{ marginBottom: 16 }}>
          You may terminate your use of the app at any time by uninstalling it from your Shopify admin.
          Upon uninstallation, your data will be deleted within 48 hours as described in our Privacy Policy.
        </p>

        <h2 style={{ fontSize: 20, fontWeight: 600, marginTop: 32, marginBottom: 12 }}>8. Changes to Terms</h2>
        <p style={{ marginBottom: 16 }}>
          We reserve the right to update these Terms of Service at any time. Material changes will be
          communicated through the app or via email. Continued use after changes constitutes acceptance.
        </p>

        <h2 style={{ fontSize: 20, fontWeight: 600, marginTop: 32, marginBottom: 12 }}>9. Contact</h2>
        <p style={{ marginBottom: 16 }}>
          For questions about these Terms, contact us at: <strong>support@magetechsol.com</strong>
        </p>
      </div>
    </div>
  );
}
